### PR TITLE
feat: 🎸 Support for TypeScript

### PR DESCRIPTION
**Pull request by SeanGroff**
✅ Closes: #244

Going to mark this PR as a Draft since I ran out of time to do more thorough testing. This seems to work as expected. I might be missing some library types packages.

Would appreciate it if anyone else would be so kind to pull these changes down and test them out.

### CODE REVIEW

**Comment by caleboleary** [comment]
@SeanGroff I pulled this & converted SQFormDialog (quick & messy) to TS - storybook was broken, but changing the webPackFinal in it's main.js to the following seems to fix it:

`webpackFinal: config => {
    config.module.rules = [
      ...config.module.rules,
      {
        test: /.jsx?$|.tsx?$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: [
              '@babel/preset-env',
              '@babel/preset-typescript',
              '@babel/preset-react'
            ]
          }
        }
      }
    ];

    return config;
  }`

**Comment by caleboleary** [comment]
Also, FYI, I had to force TS to ignore some of the JS imports that it can't get typings from like this: 
```
// @ts-ignore
import SQFormDialogInner from './SQFormDialogInner';
// @ts-ignore
import {useInitialRequiredErrors} from '../../hooks/useInitialRequiredErrors';
```

**Comment by codyarose** [comment]
Found a few things:

- This could be added to `.eslintrc.json`
```js
"extends": [
    ...
    "plugin:@typescript-eslint/recommended"
  ],
```

- For tests to work, 
    - `ts-jest` and some jest config changes need to be added, https://basarat.gitbook.io/typescript/intro-1/jest
    - `@types/testing-library__jest-dom` for the jest matcher types

**Comment by caleboleary** [comment]
Screen Shot 2021-05-25 at 11 02 22 AM

npm packed it into SRTS2 and I'm getting type warnings! 

Also, storybook looks to be working well and grabbing types for the controls panel. Nice!

**Comment by codyarose** [comment]
@SeanGroff Would this be considered a breaking change for any projects that use TS because of the added types? If they aren't using the proper types it could cause errors that would prevent a build

**Comment by caleboleary** [comment]
In our project, I had a file at root `declare module '@selectquotelabs/sqform'; ` that prevented any type warnings at all for the lib, had to remove it to receive any. I *think* I could theoretically upgrade to a TS based sqform, leave that file there, and still use the wrong types somewhere if I was, but not positive.

**Comment by codyarose** [comment]
> In our project, I had a file at root `declare module '@selectquotelabs/sqform'; ` that prevented any type warnings at all for the lib, had to remove it to receive any. I _think_ I could theoretically upgrade to a TS based sqform, leave that file there, and still use the wrong types somewhere if I was, but not positive.

Ah, yeah the same was true when I tried it in my project. So in that case we it wouldn't be a breaking change, but they'd need to know about remove that `d.ts` file in order to unblock the types

**Comment by SeanGroff** [comment]
> > In our project, I had a file at root `declare module '@selectquotelabs/sqform'; ` that prevented any type warnings at all for the lib, had to remove it to receive any. I _think_ I could theoretically upgrade to a TS based sqform, leave that file there, and still use the wrong types somewhere if I was, but not positive.
> 
> Ah, yeah the same was true when I tried it in my project. So in that case it wouldn't be a breaking change, but they'd need to know about removing that `d.ts` file (if it exists) in order to unblock the types

Ah yes....I think the right thing to do is NOT merge this to `master` until we've fully converted over to TypeScript.
So when we create an issue with a task list we need to make sure to specify the instructions of working against this branch, and PRing to this branch.

Then once we're fully migrated to TypeScript, merge this PR

**Comment by codyarose** [comment]
> I don't think we want to tell consumers to manually add a .d.ts file. Then remove it at a later point.

True. I assumed that if anyone is using this library with TS they already have a `d.ts` for it, and if they're using it with JS they won't have typechecking so it wouldn't matter.

**Comment by codyarose** [comment]
Updated from master to fix the merge conflicts

**Comment by hvilander** [comment]
Resolved some merge conflicts with that merge, it was only consuming the onTertiaryClick in our dialog so I figured it was safe to change the relevant propTypes into types. Also I managed to commit with formatting issues, pushed that change as well.

**Review by 20BBrown14 — APPROVED** [review]

**Review by hvilander — APPROVED** [review]

**Review by caleboleary — APPROVED** [review]

**Pull request merged**
