### PR TITLE
fix: 🐛 change components to use `FormControl` for state props

### PR DESCRIPTION
**Pull request by codyarose**
Inputs, labels, and helper text will get error, disabled, and required
state from `FormControl`. Reduces duplication, functionality remains the
same

https://www.loom.com/share/bf0424fdf5e5423fa65d9234f73c3b1d

✅ Closes: #160

### CODE REVIEW

**Comment by SeanGroff** [comment]
@codyarose A wild merge conflict appears 👻

**Comment by codyarose** [comment]
@SeanGroff Should be good now

**Review by 20BBrown14 — APPROVED** [review]

**Comment by SeanGroff** [comment]
@codyarose Can you take a look at the questions I had around the Asterix classes?
I wasn't sure what those are doing. I know Nemeth doesn't want to render an asterisk for required fields.

**Comment by codyarose** [comment]
> @codyarose Can you take a look at the questions I had around the Asterix classes?
> I wasn't sure what those are doing. I know Nemeth doesn't want to render an asterisk for required fields.

Oh, I can't find where those questions are, but the classes are there to make the asterisk not render. For some reason `FormLabel` makes them appear while `InputLabel` does not, so the class makes the asterisk behave the way it does in `InputLabel`.

**Review by SeanGroff — COMMENTED** [review]
> > @codyarose Can you take a look at the questions I had around the Asterix classes?
> > I wasn't sure what those are doing. I know Nemeth doesn't want to render an asterisk for required fields.
> 
> Oh, I can't find where those questions are, but the classes are there to make the asterisk not render. For some reason `FormLabel` makes them appear while `InputLabel` does not, so the class makes the asterisk behave the way it does in `InputLabel`.

TIL, good to know!

**Review by SeanGroff — APPROVED** [review]
Awesome sauce!

**Pull request merged**
