### PR TITLE
fix: 🐛 Next button logic to look at current step values to enabled/disabled SSC-115

### PR DESCRIPTION
**Pull request by Chris-Boyle**
✅ Closes: #75

Updated the next button enabled/disabled logic.  It now only looks at the current steps values to see if any have been set.  Before it was looking at all values from all steps.  

The touched property is still being set on all fields when the onSubmit is fired in the form.
If we have initial values then the next button will be enabled.

Loom https://www.loom.com/share/0def27c6e270412db50018b750deab0a

### CODE REVIEW

**Review by SeanGroff — APPROVED** [review]
Awesome. The last point you made in the Loom video about the fields being touched in Formik, is an existing issue. I've got the fixes locally, I just need to spend more time testing edge cases.

Coming Soon ™️

**Comment by Chris-Boyle** [comment]
> spend

As soon as the next button is clicked the onSubmit fires and somewhere down in Formik land the state is set to touched for all fields.  It would also be nice to reset the dirty state when the Next button is clicked.  The only thing I have found so far is using the resetForm function from useFormikContext.

**Comment by Chris-Boyle** [comment]
> Awesome. The last point you made in the Loom video about the fields being touched in Formik, is an existing issue. I've got the fixes locally, I just need to spend more time testing edge cases.
> 
> Coming Soon ™️

As soon as the next button is clicked the onSubmit fires and somewhere down in Formik land the state is set to touched for all fields.  It would also be nice to reset the dirty state when the Next button is clicked.  The only thing I have found so far is using the resetForm function from useFormikContext.

**Comment by SeanGroff** [comment]
> > Awesome. The last point you made in the Loom video about the fields being touched in Formik, is an existing issue. I've got the fixes locally, I just need to spend more time testing edge cases.
> 
> > 
> 
> > Coming Soon ™️
> 
> 
> 
> As soon as the next button is clicked the onSubmit fires and somewhere down in Formik land the state is set to touched for all fields.  It would also be nice to reset the dirty state when the Next button is clicked.  The only thing I have found so far is using the resetForm function from useFormikContext.

Setting the nextState with resetForm might be what you're looking for. Take a peak. https://formik.org/docs/api/formik#resetform-nextstate-partialformikstatevalues--void

**Pull request merged**
