### PR TITLE
feat: 🎸 Rename SQFormCheckboxGroup and replace it

### PR DESCRIPTION
**Pull request by 20BBrown14**
Renamed SQFormCheckboxGroup(Item) to SQFormInclusionList(Item) and readd
SQFormCheckboxGroup(Item) to creage a checkbox group to be used within
SQForm and other form elements

BREAKING CHANGE: 🧨 Rename SQFormCheckboxGroup(Item) to SQFormInclusionList(Item)

Diff is pretty bad since we reused a file.

✅ Closes: #101

Look at this loom! https://www.loom.com/share/0373e3e4221b4a04a60c5c1568477410

Screen Shot 2021-03-03 at 10 46 30 AM

### CODE REVIEW

**Review by SeanGroff — APPROVED** [review]
This looks great! Nice work @20BBrown14 🚀

**Comment by 20BBrown14** [comment]
> If you have not yet done so, can you warn the Squad PM and tech lead that will be effected by this breaking change so they account for it when the time comes to update their SQForm version?

Taken care of. I let Danish S know who is the tech lead on the one project i found that used the old SQFormCheckboxGroup

**Review by codyarose — CHANGES_REQUESTED** [review]
Looks great!
issue: The only thing I see that may be missing is error handling on the form components using `isFieldError` from `useForm`

**Review by lucas-homer — APPROVED** [review]

**Comment by 20BBrown14** [comment]
> Looks great!
> issue: The only thing I see that may be missing is error handling on the form components using `isFieldError` from `useForm`

I'm not sure that applies to this component. MUI doesn't provide an error field. Not from what I can see at least. And it makes sense intuitively that a checkbox group wouldn't have an error other minimum selected, which can be provided through yup.

If a user isn't allowed to select specific combinations then the consumer of this component should be listening for the changes and dynamically disable options as appropriate. 

Did you have a specific case in mind about why we would need to utilize isFieldError in another capacity besides the HelperTextComponent?

**Comment by codyarose** [comment]
> > Looks great!
> > issue: The only thing I see that may be missing is error handling on the form components using `isFieldError` from `useForm`
> 
> I'm not sure that applies to this component. MUI doesn't provide an error field. Not from what I can see at least. And it makes sense intuitively that a checkbox group wouldn't have an error other minimum selected, which can be provided through yup.
> 
> If a user isn't allowed to select specific combinations then the consumer of this component should be listening for the changes and dynamically disable options as appropriate.
> 
> Did you have a specific case in mind about why we would need to utilize isFieldError in another capacity besides the HelperTextComponent?

Okay, I looked through the MUI docs more and I see what you mean 👍

**Pull request merged**
