### PR TITLE
feat: 🎸 Added showTooltip and tooltipText props to SQFormMultiSelect

### PR DESCRIPTION
**Pull request by gdoohen1**
✅ Closes: #313

Loom https://www.loom.com/share/39bfca62199c45aeb4e5f708ff751fe4

### CODE REVIEW

**Review by SeanGroff — COMMENTED** [review]
@gdoohen1 Code LGTM!
Can you update this components story in Storybook to add controls for these 2 new props?
This would show the new functionality and something to show off in a brief Loom

**Comment by gdoohen1** [comment]
> @gdoohen1 Code LGTM!
> Can you update this components story in Storybook to add controls for these 2 new props?
> This would show the new functionality and something to show off in a brief Loom

@SeanGroff I went to go do that and the story for this component had a controls panel that allowed live editing for all the props so I didn't update the storybook but I will add a loom!

**Comment by codyarose** [comment]
> I went to go do that and the story for this component had a controls panel that allowed live editing for all the props so I didn't update the storybook but I will add a loom!

That's one of the great things about Storybook Controls 😎 
The controls are automatically built from the component's props, so you don't have to do anything extra when props change -- unless you want to customize how the control works in the story.

**Review by codyarose — APPROVED** [review]

**Review by lucas-homer — APPROVED** [review]
woooo! thank you!

**Pull request merged**
