### PR TITLE
refactor: 💡 add generics to useForm

### PR DESCRIPTION
**Pull request by codyarose**
This is what I've come up with so far - it seems to be working okay for my tests with SQFormTextField, but not quite right for SQFormDropdown (cc @SeanGroff )

https://www.loom.com/share/579531579466421885d6a3583d68265a

✅ Closes: #337

### CODE REVIEW

**Comment by SeanGroff** [comment]
Thanks you @codyarose for taking on this challenge 🚀 ❤️

**Comment by codyarose** [comment]
> Thanks you @codyarose for taking on this challenge 🚀 ❤️ 

It's a challenge for sure. The dropdown change handler is really throwing me off

**Comment by SeanGroff** [comment]
> > Thanks you @codyarose for taking on this challenge 🚀 ❤️
> 
> It's a challenge for sure. The dropdown change handler is really throwing me off

When I was reading about this issue, MUI mentioned the `onChange` for the `<Select>` component is completely different than the `onChange` of the rest of the MUI components.

Should we expose a `handleSelectChange` hook in addition to `onChange` in the `useForm` hook? (If we can't solve this challenge with generics)

**Comment by codyarose** [comment]
> Should we expose a `handleSelectChange` hook in addition to `onChange` in the `useForm` hook? (If we can't solve this challenge with generics)

I've been trying to implement that for a bit now and thought I had it figured out, but still errors...
image
I've used the exact props it expects (`SelectProps['onChange']`) and it still somehow gets 
```ts
((event: ChangeEvent<{ name?: string | undefined; value: unknown; }>, child: ReactNode) => void) | ChangeEventHandler<HTMLInputElement | HTMLTextAreaElement> | undefined
```

I'm not sure how the `ChangeEventHandler<HTMLInputElement | HTMLTextAreaElement>` is getting in there

**Comment by codyarose** [comment]
@SeanGroff The main issue appears to be that Formik expects the `onChange` to be in one shape and the Mui components expect it to be in another shape. `Select` passes along a `child` prop with the `event`, `Checkbox` passes along a `checked` prop with the `event`, etc... while Formik just expects an `event`

I think something like this will work:
```ts
interface UseFormParam<ChangeEventType> {
  name: string;
  isRequired: boolean;
  onBlur?: React.FocusEventHandler;
  onChange?: (
    event: React.ChangeEvent<ChangeEventType>,
    ...args: any[]
  ) => void;
}
```
There's a rule to allow `any[]` on rest parameters, which I think is a valid option because sometimes you can't know exactly what all the parameters will be

**Comment by codyarose** [comment]
https://www.loom.com/share/294836a04eb247c4b43168261b920c16

**Pull request closed without merging**
