### PR TITLE
chore: 🤖 ignore `@storybook/addon-docs` in jest config

### PR DESCRIPTION
**Pull request by codyarose**
The tests using stories were failing because
`@storybook/addon-docs/blocks` is using esm, which jest currently does
not understand. I've added that package to the `transformIgnorePatterns`
list in the jest config to solve that, but also had to change the
`.babelrc` to `babel.config.json` due to updates in Babel v7

Apparently, the deal with Babel 7 is that it no longer automatically loads the `.babelrc`. It now has the concept of a `root` directory, which is the current working directory by default, where it looks for a `babel.config.json` file. With this change Jest will be able to properly load the babel config.

References: 
- [similar situation with a different storybook package using esm](https://github.com/storybookjs/storybook/issues/9470#issuecomment-574790318)
- [Babel 7 config files docs](https://babeljs.io/docs/en/config-files#project-wide-configuration)
- [Jest issue demonstrating `.babelrc` vs `babel.config.js` when using `transformIgnorePatterns`](https://github.com/facebook/jest/issues/10256)

✅ Closes: #204

### CODE REVIEW

**Comment by SeanGroff** [comment]
@codyarose Do we want to bump our package version for this fix? Jest shouldn't affect our consumers.
Should this be a `chore` commit?

**Comment by codyarose** [comment]
> @codyarose Do we want to bump our package version for this fix? Jest shouldn't affect our consumers.
> Should this be a `chore` commit?

Ah, right.. I suppose that's true - as long as the change from `.babelrc` &#8594; `babel.config.json` doesn't affect anything?

**Comment by SeanGroff** [comment]
> > @codyarose Do we want to bump our package version for this fix? Jest shouldn't affect our consumers.
> > Should this be a `chore` commit?
> 
> Ah, right.. I suppose that's true - as long as the change from `.babelrc` → `babel.config.json` doesn't affect anything?

Since they are both JSON syntax nothing should be affected. The consumer transpiles their own code.

**Comment by codyarose** [comment]
@SeanGroff Okay I amended the commit locally and pushed it up. That should do it, right?

**Review by SeanGroff — APPROVED** [review]

**Pull request merged**
