### PR TITLE
refactor: 💡 Convert SQFormResetInitialValuesButton to typescript Ref #244

### PR DESCRIPTION
**Pull request by mishaqkhan**
Loom of it functioning in storybook:
https://www.loom.com/share/a02b663efdfa4f2fb9c73c524e4a93cc

### CODE REVIEW

**Review by gdoohen1 — APPROVED** [review]
Looks good. Can you add a TODO in here somewhere to remove ResetForm and the casting on lines 40 and 42 once `useFormButtom` is TSified.

**Comment by mishaqkhan** [comment]
> TSified



> Looks good. Can you add a TODO in here somewhere to remove ResetForm and the casting on lines 40 and 42 once `useFormButtom` is TSified.

Add

**Comment by mishaqkhan** [comment]
> Looks good. Can you add a TODO in here somewhere to remove ResetForm and the casting on lines 40 and 42 once `useFormButtom` is TSified.

Add TODO comment to remove ResetForm and the casting on lines 40 and 42 once useFormButtom is TSified.

**Comment by mishaqkhan** [comment]
I mistakenly closed this PR so I am going to create another PR now.

**Pull request closed without merging**
