### PR TITLE
Issue 788/remove material UI 4 packages

### PR DESCRIPTION
**Pull request by aharpt**
This PR cannot be merged until https://github.com/SelectQuoteLabs/SQForm/pull/787 is merged.  Most of the current diff is changes from that PR.

MUI5 Storybook working

### CODE REVIEW

**Comment by laurelbean** [comment]
Since this is the last step, I think it would be good if multiple people pulled down the code and did a spot check for any potential issues from the upgrade.

**Comment by aharpt** [comment]
> Since this is the last step, I think it would be good if multiple people pulled down the code and did a spot check for any potential issues from the upgrade.

@laurelbean Agreed.  I have already created one issue related to some spacing issues which I believe has to do with some changes on the MUI-side to the `Grid` component.

**Review by 20BBrown14 — APPROVED** [review]

**Comment by aharpt** [comment]
Went through my own smoke-test of the app and covered my findings of things that need/may need to be addressed.  See loom if interested: https://www.loom.com/share/872df263bf1440fba618f5f559c656d8.

**Comment by laurelbean** [comment]
I just tried pulling in MUI v5 of SSC and the local build of this branch into SC3. I had to make a few adjustments for the breaking changes, but it's compiling.
Screen Shot 2022-08-30 at 9 59 25 AM
Obviously needs some more work on styling, but I think this is a good indication that it will work.

**Comment by 20BBrown14** [comment]
> Obviously needs some more work on styling, but I think this is a good indication that it will work.

The biggest thing is make sure you pulled the new css files from SSC into your local branch.

Additionally, I've got a "somewhat" contrived project using the ancillary app that I'm using to testing. Am having an issue with one of the packages that I still need to resolve. But so far this upgrade is looking promissing.

**Comment by aharpt** [comment]
> I just tried pulling in MUI v5 of SSC and the local build of this branch into SC3. I had to make a few adjustments for the breaking changes, but it's compiling. Screen Shot 2022-08-30 at 9 59 25 AM Obviously needs some more work on styling, but I think this is a good indication that it will work.

@laurelbean Is this for the SSC MUI5 migration work or for SQForm?

**Comment by 20BBrown14** [comment]
@laurelbean @aharpt how do we feel about merging this and continuing to test?

**Comment by laurelbean** [comment]
@aharpt I pulled in both projects with MUI 5. Using a locally built version of SQForm and the latest SSC version.

@20BBrown14 Yeah, there's still the feature branch into main to go so we should be good to push this one.

**Pull request merged**
