### PR TITLE
fix: 🐛 correct error state when initial values provided

### LINKED ISSUE #89: Different validation errors onChange and onBlur
I've noticed a weird thing with some validation. If a field is required AND has a specific answer required to be valid the UI doesn't update with onChange properly. Instead when it blurs it shows the proper validation message. I've created a branch that recreates the issue in Storybook. Also there's a loom.

Branch: https://github.com/SelectQuoteLabs/SQForm/compare/form_validation_showcase

Loom: https://www.loom.com/share/e40a450e6da3459a8828b83086bdf0bf

### PR DESCRIPTION
**Pull request by codyarose**
Validation errors aren't showing on mount because `isFieldError` uses
`isTouched`. The field won't be considered touched until the user clicks
it, which is why we're seeing the current behavior. If we use `hasValue`
it will show those errors when the field has an initial value.

https://www.loom.com/share/2049ee6738ee477dabb9df1bce9d5596

Also fixes #89: https://www.loom.com/share/1b49b2a0125d4fd8b082097b31c950c0

✅ Closes: #165, #89, #147

### CODE REVIEW

**Comment by codyarose** [comment]
> Nice fix! 
> Would this also be a good candidate for a test in the future? 
> 
> Test to ensure proper error State on initial load?

Yes, we should create a method for testing the error state that can be reused across all the component tests to ensure that their behavior is consistent.

**Comment by codyarose** [comment]
> It's been a hot minute since I looked at it but I think this might fix #89 as well.

Yep, confirmed that this will solve that issue as well

**Review by SeanGroff — APPROVED** [review]
Those closed issues!!
Great fix @codyarose 🚀 🚀 🚀

**Pull request merged**
