### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by laurelbean**
This will add Lucas and myself as approving reviewers on PRs.

### CODE REVIEW

**Review by aharpt — APPROVED** [review]

**Review by 20BBrown14 — APPROVED** [review]

**Comment by 20BBrown14** [comment]
Will this commit cause any weird deployments?

**Comment by laurelbean** [comment]
@20BBrown14 I haven't done changes to `.github` files before, so I'm not 100% sure, but I wouldn't think so? I'm not changing any code. There is potential for it to kick off a new build, but it would just be building the exact same as what's already out there.

**Comment by 20BBrown14** [comment]
> @20BBrown14 I haven't done changes to `.github` files before, so I'm not 100% sure, but I wouldn't think so? I'm not changing any code. There is potential for it to kick off a new build, but it would just be building the exact same as what's already out there.

Makes sense to me. I wonder if we should make sure this is a chore commit or similar just in case so we don't bump the version for no reason.

**Comment by laurelbean** [comment]
Yeah, probably safer. I'll close this and push a chore commit instead.

**Pull request closed without merging**
