### PR TITLE
feat: 🎸 adding 20px padding to DialogContent used by the SQFormDialog component

### PR DESCRIPTION
**Pull request by Chris-Boyle**
Adding 20px padding to DialogContent used by the SQFormDialog component.

BREAKING CHANGE: 🧨 Changed SQFormDialog content padding to 20px from 8px 24px

✅ Closes: #88

Loom: https://www.loom.com/share/6ead5c0298f24e4f80533f2d3e05d1af

### CODE REVIEW

**Comment by 20BBrown14** [comment]
The breaking change section should include what the breaking change actually was, it'll make its way into the changelog

**Comment by Chris-Boyle** [comment]
> The breaking change section should include what the breaking change actually was, it'll make its way into the changelog

This commit tool is so silly sometimes.  I wish it was more intuitive and user friendly.

**Comment by 20BBrown14** [comment]
> > The breaking change section should include what the breaking change actually was, it'll make its way into the changelog
> 
> This commit tool is so silly sometimes. I wish it was more intuitive and user friendly.

I agree. Fortunately, however, I think you should be able to do a `git reset` and then run `npm run commit` again and then do a `git push --force` to fix it. Or you could just do `git commit --amend` and change the text. I'm 99% sure (Maybe Sean knows more) it'll pull the text off the commit, whatever it is, as merge time to generate the changelog. Of course you'll need to `git push --force` after a commit amend.

**Review by codyarose — APPROVED** [review]

**Review by 20BBrown14 — APPROVED** [review]
💥

**Pull request merged**
