### PR TITLE
Convert SQFormButton.stories.test to TypeScript

### PR DESCRIPTION
**Pull request by laurelbean**
Even though SQFormButton.stories.test was previously converted to TypeScript, it didn't actually like the anys/unknown coming from the SQFormButton.stories.js file. So in order to make the test file happy, I also had to update the associated story file.
When I updated the story file, I ran into some weird build errors. That's why there are a lot of dependency updates. I had to get the correct configuration so that all the types were available.
After I got the build working, I ran the tests to make sure I hadn't broken anything, and discovered that the latest `@testing-library/user-event` had added an error if you try and `.click` an object that is not click-able. So 2 of our test cases were failing where we were trying to click a button that was disabled. So the tests started failing before we were able to assert the onClickSpy hadn't been called.

### CODE REVIEW

**Review by 20BBrown14 — APPROVED** [review]

**Comment by codyarose** [comment]
> After I got the build working, I ran the tests to make sure I hadn't broken anything, and discovered that the latest `@testing-library/user-event` had added an error if you try and `.click` an object that is not click-able. So 2 of our test cases were failing where we were trying to click a button that was disabled. So the tests started failing before we were able to assert the onClickSpy hadn't been called.

I noticed that recently as well. It seems that you can still use `fireEvent` to get the click to work: https://github.com/SelectQuoteLabs/SQForm/pull/330/files#r668230199

**Comment by laurelbean** [comment]
> > After I got the build working, I ran the tests to make sure I hadn't broken anything, and discovered that the latest `@testing-library/user-event` had added an error if you try and `.click` an object that is not click-able. So 2 of our test cases were failing where we were trying to click a button that was disabled. So the tests started failing before we were able to assert the onClickSpy hadn't been called.
> 
> I noticed that recently as well. It seems that you can still use `fireEvent` to get the click to work: https://github.com/SelectQuoteLabs/SQForm/pull/330/files#r668230199

I forgot you figured that out already! Thanks, I'll update it.
This reminds me though. The base branch (issue-244 one) is pretty out of date from the main branch now. Missing things like your `fireEvent` updates and it's also missing a few newer test files.

**Comment by codyarose** [comment]
> This reminds me though. The base branch (issue-244 one) is pretty out of date from the main branch now. Missing things like your `fireEvent` updates and it's also missing a few newer test files.

Yeah, I think it may be time to sync 244 and bite the bullet on all the merge conflicts that I'm sure will show up (cc @SeanGroff )

**Review by codyarose — APPROVED** [review]

**Comment by SeanGroff** [comment]
> > This reminds me though. The base branch (issue-244 one) is pretty out of date from the main branch now. Missing things like your `fireEvent` updates and it's also missing a few newer test files.
> 
> Yeah, I think it may be time to sync 244 and bite the bullet on all the merge conflicts that I'm sure will show up (cc @SeanGroff )

Yes we should've been syncing the  epic branch with master at least weekly 😬

**Comment by codyarose** [comment]
> Yes we should've been syncing the epic branch with master at least weekly 😬

Trying to sync it now 🤞

**Comment by laurelbean** [comment]
Attempting to merge in updates on feature branch, I can't commit now because I get warnings on `. md` files.

```/Users/laurel.bean/codebase/TypeScriptTesting/SQForm/CHANGELOG.md
  0:0  warning  File ignored because of a matching ignore pattern. Use "--no-ignore" to override

/Users/laurel.bean/codebase/TypeScriptTesting/SQForm/notes/SQFormMultiValue.md
  0:0  warning  File ignored because of a matching ignore pattern. Use "--no-ignore" to override

/Users/laurel.bean/codebase/TypeScriptTesting/SQForm/src/components/SQFormGuidedWorkflow/README.md
  0:0  warning  File ignored because of a matching ignore pattern. Use "--no-ignore" to override
```

From what I can tell, it's happening because we are sending md to prettier, lint, and git add. 
```"lint-staged": {
    "*.{js,ts,tsx,md}": [
      "prettier --write",
      "npm run lint",
      "git add"
    ]
  },
```
However we also have *.md in the `.eslintignore` file and so eslint doesn't know if we meant to lint the file or not. 
See docs: https://eslint.org/docs/user-guide/configuring/ignoring-code
But I also didn't see anyone else have this problem yet, so I'm not sure if it's related to something I've changed.

**Comment by laurelbean** [comment]
Updated the `lint-staged` command to treat .md files separately. Please let me know if there are any concerns with that.
I also fixed the 3 failing test files.

**Review by Chris-Boyle — APPROVED** [review]

**Pull request merged**
