### PR TITLE
Issue 672/fix date picker type

### PR DESCRIPTION
**Pull request by aharpt**
Fix hole in `BaseDatePickerProps`.

https://www.loom.com/share/9aa352088e9f4702af3a9db90a8c78b3

✅ Closes: #672

### CODE REVIEW

**Comment by SeanGroff** [comment]
Can we squash the commits (or whatever method works best for you) to get rid of the commit from your other PR?

**Comment by aharpt** [comment]
> Can we squash the commits (or whatever method works best for you) to get rid of the commit from your other PR?

@SeanGroff The import commit actually has to do with an inadvertent import order change in `SQFormDatePicker.tsx` which I did not want to appear in the diff.

**Comment by SeanGroff** [comment]
After looking through their source code `types` I think we can extend their `BasePickerProps` instead of manually adding one prop so this doesn't happen again with other holes in the current type.

https://github.com/mui/material-ui-pickers/blob/e875729b3492a4aedebec9f14589accc83475241/lib/src/typings/BasePicker.tsx

**Comment by aharpt** [comment]
> After looking through their source code `types` I think we can extend their `BasePickerProps` instead of manually adding one prop so this doesn't happen again with other holes in the current type.
> 
> https://github.com/mui/material-ui-pickers/blob/e875729b3492a4aedebec9f14589accc83475241/lib/src/typings/BasePicker.tsx

@SeanGroff PR is updated to reflect this change.

**Review by hvilander — APPROVED** [review]

**Review by SeanGroff — APPROVED** [review]

**Pull request merged**
